-- Run this once in Supabase Dashboard -> SQL Editor.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sku text not null,
  name text not null,
  category text not null default '',
  size text,
  color text,
  usage text,
  unit text,
  reorder numeric not null default 500,
  stock numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, sku)
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product text not null,
  type text not null check (type in ('IN', 'OUT')),
  qty numeric not null check (qty > 0),
  ref text,
  date text not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.stock_movements enable row level security;

drop policy if exists "Users manage their products" on public.products;
create policy "Users manage their products"
  on public.products for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage their movements" on public.stock_movements;
create policy "Users manage their movements"
  on public.stock_movements for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists stock_movements_user_date_idx
  on public.stock_movements (user_id, created_at desc);
